### ISSUE TITLE
Audio script

### ISSUE THREAD

**Issue by unixfx** [Youka/Macol#1]
Hi Youka.

I just used audio lua script, in audio file box (audio file to visualize) what should I write?
name of audio file with path, or just audio file name (16 bit ) with format.
 example.wav ?

Regards..

**Comment by Youka** [comment]
Just the filename/-path is enough.

There was an [example package](http://forum.aegisub.org/viewtopic.php?f=6&t=65753), but the Aegisub Lua API changed over time, so i'm not sure it still works.

**Comment by unixfx** [comment]
Yeah as you said it's not works with the recent releases of Aegisub. anyway it's ok.

Thank you.
